const knownCookies = [
    { regex: /^Hm_lpvt_/, company: "Baidu" },
    { regex: /^Hm_lvt_/, company: "Baidu" },
    { regex: /^BAIDUID/, company: "Baidu" },
    { regex: /^BVBRANDID/, company: "Bazaarvoice" },
    { regex: /^BVBRANDSID/, company: "Bazaarvoice" },
    { regex: /^BVID/, company: "Bazaarvoice" },
    { regex: /^BVSID/, company: "Bazaarvoice" },
    { regex: /^bv_metrics/, company: "Bazaarvoice" },
    { regex: /^client_bslstaid/, company: "Beslist.nl" },
    { regex: /^client_bslstmatch/, company: "Beslist.nl" },
    { regex: /^client_bslstsid/, company: "Beslist.nl" },
    { regex: /^client_bslstuid/, company: "Beslist.nl" },
    { regex: /^dc$/, company: "BetweenDigital" },
    { regex: /^betweendigital.com/, company: "betweendigital.com" },
    { regex: /^duid_update_time/, company: "Bidence" },
    { regex: /^bito/, company: "bidr.io" },
    { regex: /^bitoIsSecure/, company: "bidr.io" },
    { regex: /^tuuid/, company: "Bidswitch" },
    { regex: /^tuuid_lu/, company: "Bidswitch.net" },
    { regex: /^__kuid/, company: "BidTheatre" },
    { regex: /^_kuid_/, company: "BidTheatre" },
    { regex: /^ACH01/, company: "Bing / Microsoft" },
    { regex: /^ACL$/, company: "Bing / Microsoft" },
    { regex: /^ACLUSR/, company: "Bing / Microsoft" },
    { regex: /^ANON/, company: "Bing / Microsoft" },
    { regex: /^BFB$/, company: "Bing / Microsoft" },
    { regex: /^BFBUSR/, company: "Bing / Microsoft" },
    { regex: /^CC$/, company: "Bing / Microsoft" },
    { regex: /^childinfo/, company: "Bing / Microsoft" },
    { regex: /^kcdob/, company: "Bing / Microsoft" },
    { regex: /^kcrelid/, company: "Bing / Microsoft" },
    { regex: /^kcru/, company: "Bing / Microsoft" },
    { regex: /^MC1$/, company: "Bing / Microsoft" },
    { regex: /^MH$/, company: "Bing / Microsoft" },
    { regex: /^MSFPC/, company: "Bing / Microsoft" },
    { regex: /^MUIDB/, company: "Bing / Microsoft" },
    { regex: /^NAP$/, company: "Bing / Microsoft" },
    { regex: /^OID$/, company: "Bing / Microsoft" },
    { regex: /^OIDI/, company: "Bing / Microsoft" },
    { regex: /^OIDR/, company: "Bing / Microsoft" },
    { regex: /^pcfm/, company: "Bing / Microsoft" },
    { regex: /^ToptOut/, company: "Bing / Microsoft" },
    { regex: /^BLUEID/, company: "Blue" },
    { regex: /^ckid/, company: "Blue" },
    { regex: /^hash/, company: "Blue" },
    { regex: /^bkdc/, company: "BlueKai" },
    { regex: /^bkpa/, company: "BlueKai" },
    { regex: /^bku$/, company: "BlueKai" },
    { regex: /^tp$/, company: "Bombora" },
    { regex: /^__141_cid/, company: "Bombora" },
    { regex: /^bounceClientVisit/, company: "Bouncex" },
    { regex: /^dgzsdl08v4/, company: "Bouncex" },
    { regex: /^ab.storage.deviceId./, company: "Braze" },
    { regex: /^ab.storage.sessionId./, company: "Braze" },
    { regex: /^CMID/, company: "Casale Media" },
    { regex: /^CMPRO/, company: "Casale Media" },
    { regex: /^CMPS/, company: "Casale Media" },
    { regex: /^CMRUM3/, company: "Casale Media" },
    { regex: /^CMST/, company: "Casale Media" },
    { regex: /^_cb_ls/, company: "Chartbeat" },
    { regex: /^cognito.organization/, company: "CognitoForms" },
    { regex: /^cognito.services.a/, company: "CognitoForms" },
    { regex: /^c-plan/, company: "CognitoForms" },
    { regex: /^c-referrer/, company: "CognitoForms" },
    { regex: /^c-signup/, company: "CognitoForms" },
    { regex: /^C1$/, company: "comScore" },
    { regex: /^S1$/, company: "comScore" },
    { regex: /^UID$/, company: "ComScore" },
    { regex: /^UIDR/, company: "ComScore" },
    { regex: /^XID$/, company: "ComScore" },
    { regex: /^WRBlock/, company: "ContentSquare" },
    { regex: /^WRIgnore/, company: "ContentSquare" },
    { regex: /^WRUID/, company: "ContentSquare" },
    { regex: /^ccec_user/, company: "CookieConsent.io" },
    { regex: /^NoCookie/, company: "COPPA" },
    { regex: /^ce_need_secure_cookie/, company: "Crazy Egg" },
    { regex: /^ce_signup_partner/, company: "Crazy Egg" },
    { regex: /^ce_successful_csp_check/, company: "Crazy Egg" },
    { regex: /^cebs/, company: "Crazy Egg" },
    { regex: /^cebsp_/, company: "Crazy Egg" },
    { regex: /^ceft_variant_override/, company: "Crazy Egg" },
    { regex: /^g$/, company: "CreativeCDN" },
    { regex: /^viewer_token/, company: "csync.loopme.me" },
    { regex: /^cioFT/, company: "Customer.io" },
    { regex: /^cioLT/, company: "Customer.io" },
    { regex: /^gckp/, company: "CXense" },
    { regex: /^datatrics_customData/, company: "Datatrics" },
    { regex: /^datatrics_optin/, company: "Datatrics" },
    { regex: /^datatricsDebugger/, company: "Datatrics" },
    { regex: /^digitalAudience/, company: "Digital Audience" },
    { regex: /^vglnk.Agent.p/, company: "Disqus" },
    { regex: /^vglnk.PartnerRfsh.p/, company: "Disqus" },
    { regex: /^DotMetrics.DeviceKey/, company: "Dotmetrics" },
    { regex: /^DotMetrics.SessionCookieTemp/, company: "Dotmetrics" },
    { regex: /^DotMetrics.SessionCookieTempTimed/, company: "Dotmetrics" },
    { regex: /^DotMetrics.UniqueUserIdentityCookie/, company: "Dotmetrics" },
    { regex: /^cjae/, company: "Dotomi" },
    { regex: /^DotomiSession_/, company: "Dotomi" },
    { regex: /^DotomiStatus/, company: "Dotomi" },
    { regex: /^DotomiSync/, company: "Dotomi" },
    { regex: /^DotomiUser/, company: "Dotomi" },
    { regex: /^dtm_gdpr_delete/, company: "Dotomi" },
    { regex: /^dtm_gpc_optout/, company: "Dotomi" },
    { regex: /^dtm_tcdata/, company: "Dotomi" },
    { regex: /^dtm_tcdata_exp/, company: "Dotomi" },
    { regex: /^dtm_token/, company: "Dotomi" },
    { regex: /^dtm_token_exp/, company: "Dotomi" },
    { regex: /^dtm_token_sc/, company: "Dotomi" },
    { regex: /^dtm_user_id/, company: "Dotomi" },
    { regex: /^dtm_user_id_sc/, company: "Dotomi" },
    { regex: /^IDE$/, company: "DoubleClick" },
    { regex: /^test_cookie/, company: "DoubleClick" },
    { regex: /^APC$/, company: "DoubleClick" },
    { regex: /^ar_debug/, company: "DoubleClick" },
    { regex: /^DSID/, company: "DoubleClick" },
    { regex: /^FLC$/, company: "DoubleClick" },
    { regex: /^GoogleAdServingTest/, company: "DoubleClick" },
    { regex: /^RUL$/, company: "DoubleClick" },
    { regex: /^dm_last_page_view/, company: "Duda" },
    { regex: /^dm_last_visit/, company: "Duda" },
    { regex: /^dm_this_page_view/, company: "Duda" },
    { regex: /^dm_timezone_offset/, company: "Duda" },
    { regex: /^dm_total_visits/, company: "Duda" },
    { regex: /^apmsessionid/, company: "Dynatrace" },
    { regex: /^dtCookie/, company: "Dynatrace" },
    { regex: /^dtDisabled/, company: "Dynatrace" },
    { regex: /^dtLatC/, company: "Dynatrace" },
    { regex: /^dtPC/, company: "DynaTrace" },
    { regex: /^dtSa/, company: "DynaTrace" },
    { regex: /^dtValidationCookie/, company: "Dynatrace" },
    { regex: /^rxVisitor/, company: "Dynatrace" },
    { regex: /^rxvt/, company: "DynaTrace" },
    { regex: /^SRV$/, company: "Dynatrace" },
    { regex: /^ssoCSRFCookie/, company: "Dynatrace" },
    { regex: /^STVID/, company: "ElasticSuite" },
    { regex: /^ep$/, company: "Emetric" },
    { regex: /^pid_short/, company: "Emetric" },
    { regex: /^pid_signature/, company: "Emetric" },
    { regex: /^v_usr/, company: "E-volution.ai" },
    { regex: /^pb-tracking-id/, company: "Ex.co" },
    { regex: /^ezoadgid_/, company: "Ezoic" },
    { regex: /^ezopvc_/, company: "Ezoic" },
    { regex: /^ezoref_/, company: "Ezoic" },
    { regex: /^ezosuibasgeneris-1/, company: "Ezoic" },
    { regex: /^ezosuigeneris/, company: "Ezoic" },
    { regex: /^ezouid_/, company: "Ezoic" },
    { regex: /^ezovid_/, company: "Ezoic" },
    { regex: /^ezovuuid_/, company: "Ezoic" },
    { regex: /^ezovuuidtime_/, company: "Ezoic" },
    { regex: /^ezux_et_/, company: "Ezoic" },
    { regex: /^ezux_ifep_/, company: "Ezoic" },
    { regex: /^ezux_lpl_/, company: "Ezoic" },
    { regex: /^ezux_tos_/, company: "Ezoic" },
    { regex: /^aks$/, company: "Facebook" },
    { regex: /^aksb/, company: "Facebook" },
    { regex: /^c_user/, company: "Facebook" },
    { regex: /^campaign_click_url/, company: "Facebook" },
    { regex: /^csm$/, company: "Facebook" },
    { regex: /^datr/, company: "Facebook" },
    { regex: /^dbln/, company: "Facebook" },
    { regex: /^ddid/, company: "Facebook" },
    { regex: /^fr$/, company: "Facebook" },
    { regex: /^ick$/, company: "Facebook" },
    { regex: /^js_ver/, company: "Facebook" },
    { regex: /^locale$/, company: "Facebook" },
    { regex: /^lu$/, company: "Facebook" },
    { regex: /^m_user/, company: "Facebook" },
    { regex: /^oo$/, company: "Facebook" },
    { regex: /^pl$/, company: "Facebook" },
    { regex: /^rc$/, company: "Facebook" },
    { regex: /^s$/, company: "Facebook" },
    { regex: /^sb$/, company: "Facebook" },
    { regex: /^sfau/, company: "Facebook" },
    { regex: /^usida/, company: "Facebook" },
    { regex: /^xs$/, company: "Facebook" },
    { regex: /^_fbp/, company: "Facebook" },
    { regex: /^fbsr_/, company: "Facebook" },
    { regex: /^pluto/, company: "Fastclick" },
    { regex: /^pluto2/, company: "Fastclick" },
    { regex: /^ljt_reader/, company: "Federated Media Publishing" },
    { regex: /^DSP_UID/, company: "Fidelity-media.com" },
    { regex: /^frosmo_keywords/, company: "Frosmo Platform" },
    { regex: /^DG_HID/, company: "Funda" },
    { regex: /^DG_IID/, company: "Funda" },
    { regex: /^DG_SID/, company: "Funda" },
    { regex: /^DG_UID/, company: "Funda" },
    { regex: /^DG_ZID/, company: "Funda" },
    { regex: /^DG_ZUID/, company: "Funda" },
    { regex: /^Gdyn/, company: "Gemius" },
    { regex: /^hasGmid/, company: "Gigya" },
    { regex: /^ucid/, company: "Gigya" },
    { regex: /^gig3pctest/, company: "Gigya" },
    { regex: /^COMPASS/, company: "Google Ads" },
    { regex: /^cookies_accepted/, company: "Google Ads" },
    { regex: /^DV$/, company: "Google Ads" },
    { regex: /^FPGCLDC/, company: "Google Ads" },
    { regex: /^GN_PREF/, company: "Google Ads" },
    { regex: /^HSID/, company: "Google Ads" },
    { regex: /^LSID/, company: "Google Ads" },
    { regex: /^NID$/, company: "Google Ads" },
    { regex: /^OSID/, company: "Google Ads" },
    { regex: /^OTZ$/, company: "Google Ads" },
    { regex: /^pagead\\1p-user-list/, company: "Google Ads" },
    { regex: /^SNID/, company: "Google Ads" },
    { regex: /^ADS_VISITOR_ID/, company: "Google Ads" },
    { regex: /^Conversion/, company: "Google Ads" },
    { regex: /^FPGCLAW/, company: "Google Ads" },
    { regex: /^FPGCLGB/, company: "Google Ads" },
    { regex: /^UULE/, company: "Google Ads" },
    { regex: /^_gcl_au/, company: "Google AdSence" },
    { regex: /^ACLK_DATA/, company: "Google Adsense" },
    { regex: /^GED_PLAYLIST_ACTIVITY/, company: "Google Adsense" },
    { regex: /^_gcl_aw/, company: "Google Adwords" },
    { regex: /^_ga_/, company: "Google Analytics" },
    { regex: /^_gat_/, company: "Google Analytics" },
    { regex: /^AMP_TOKEN/, company: "Google Analytics" },
    { regex: /^FPAU/, company: "Google Analytics" },
    { regex: /^FPID/, company: "Google Analytics" },
    { regex: /^FPLC/, company: "Google Analytics" },
    { regex: /^cto_lwid/, company: "Google Double-click" },
    { regex: /^permutive-id/, company: "Google Double-click" },
    { regex: /^permutive-session/, company: "Google Double-click" },
    { regex: /^OGP$/, company: "Google Maps" },
    { regex: /^OGPC/, company: "Google Maps" },
    { regex: /^_ga$/, company: "Google Analytics" },
    { regex: /^_gid/, company: "Google Analytics" },
    { regex: /^__utmc/, company: "Google Analytics" },
    { regex: /^_gat_gtag_/, company: "Google Analytics" },
    { regex: /^__utma/, company: "Google Analytics" },
    { regex: /^__utmz/, company: "Google Analytics" },
    { regex: /^_gat/, company: "Google Analytics" },
    { regex: /^_utmv/, company: "Google Analytics" },
    { regex: /^_gcl/, company: "Google Analytics" },
    { regex: /^_gat_UA/, company: "Google Analytics" },
    { regex: /^__utmb/, company: "Google Analytics" },
    { regex: /^__utmt_UA-/, company: "Google Analytics" },
    { regex: /^_gat_UA-/, company: "Google Analytics" },
    { regex: /^__utmt/, company: "Google Analytics" },
    { regex: /^_gac_/, company: "Google Analytics" },
    { regex: /^PAIDCONTENT/, company: "Google Surveys" },
    { regex: /^GRV_BHV_BRND_/, company: "Groovinads" },
    { regex: /^GRV_BHV_DATE/, company: "Groovinads" },
    { regex: /^GRV_BHV_IDCAT/, company: "Groovinads" },
    { regex: /^GRV_BHV_IDCC/, company: "Groovinads" },
    { regex: /^GRV_BHV_SKU/, company: "Groovinads" },
    { regex: /^GRV_BHV_UID/, company: "Groovinads" },
    { regex: /^GRV_google/, company: "Groovinads" },
    { regex: /^GRV_IDU/, company: "Groovinads" },
    { regex: /^NPA$/, company: "Groovinads" },
    { regex: /^ibkukiuno/, company: "Group M" },
    { regex: /^ibkukinet/, company: "Group M" },
    { regex: /^_hjTLDTest/, company: "Hotjar" },
    { regex: /^_hjAbsoluteSessionInProgress/, company: "Hotjar" },
    { regex: /^_hjSession_/, company: "Hotjar" },
    { regex: /^_hjSessionUser_/, company: "Hotjar" },
    { regex: /^_hjFirstSeen/, company: "Hotjar" },
    { regex: /^hjredir/, company: "Hotjar" },
    { regex: /^hubspotapi/, company: "Hubspot" },
    { regex: /^hubspotutk/, company: "Hubspot" },
    { regex: /^messagesUtk/, company: "Hubspot" },
    { regex: /^callback/, company: "ID5" },
    { regex: /^car$/, company: "ID5" },
    { regex: /^cf$/, company: "ID5" },
    { regex: /^cip$/, company: "ID5" },
    { regex: /^cnac/, company: "ID5" },
    { regex: /^id5$/, company: "ID5" },
    { regex: /^ih-cf-cache/, company: "iHerb" },
    { regex: /^ih-exp-user-id/, company: "iHerb" },
    { regex: /^ihr-ea-time/, company: "iHerb" },
    { regex: /^ih-preference/, company: "iHerb" },
    { regex: /^iher-pref1/, company: "iHerb" },
    { regex: /^um$/, company: "Improve Digital" },
    { regex: /^umeh/, company: "Improve Digital" },
    { regex: /^CTK$/, company: "Indeed" },
    { regex: /^ctkgen/, company: "Indeed" },
    { regex: /^INDEED_CSRF_TOKEN/, company: "Indeed" },
    { regex: /^jasx_pool_id/, company: "Indeed" },
    { regex: /^pagead\/conv/, company: "Indeed" },
    { regex: /^i00$/, company: "infOnline" },
    { regex: /^__insp_targlpu/, company: "Inspectlet" },
    { regex: /^__insp_nv/, company: "Inspectlet" },
    { regex: /^__insp_pad/, company: "Inspectlet" },
    { regex: /^__insp_wid/, company: "Inspectlet" },
    { regex: /^__insp_targlpt/, company: "Inspectlet" },
    { regex: /^__insp_sid/, company: "Inspectlet" },
    { regex: /^__insp_dct/, company: "Inspectlet" },
    { regex: /^__insp_slim/, company: "Inspectlet" },
    { regex: /^ds_user_id/, company: "Instagram" },
    { regex: /^fbm_/, company: "Instagram" },
    { regex: /^ig_cb/, company: "Instagram" },
    { regex: /^ig_did/, company: "Instagram" },
    { regex: /^sessionid/, company: "Instagram" },
    { regex: /^shbid/, company: "Instagram" },
    { regex: /^shbts/, company: "Instagram" },
    { regex: /^intercom-device-id-/, company: "Intercom" },
    { regex: /^intercom-id-/, company: "Intercom" },
    { regex: /^intercom-session-/, company: "Intercom" },
    { regex: /^iutk/, company: "Issuu" },
    { regex: /^jvxsync/, company: "Jivox" },
    { regex: /^jvxbksync/, company: "Jivox" },
    { regex: /^jpxumaster/, company: "justpremium.com" },
    { regex: /^jpxumatched/, company: "justpremium.com" },
    { regex: /^KelkooID/, company: "Kelkoo" },
    { regex: /^CMSLandingPageLoaded/, company: "Kentico" },
    { regex: /^CMSUserPage/, company: "Kentico" },
    { regex: /^CurrentContact/, company: "Kentico" },
    { regex: /^VisitorStatus/, company: "Kentico" },
    { regex: /^_lfa_test_cookie_stored/, company: "Leadfeeder" },
    { regex: /^_lfa/, company: "Leadfeeder" },
    { regex: /^ABSELB/, company: "LinkedIN" },
    { regex: /^BizographicsOptOut/, company: "LinkedIN" },
    { regex: /^BizoID/, company: "LinkedIN" },
    { regex: /^brwsr/, company: "LinkedIN" },
    { regex: /^bscookie/, company: "LinkedIN" },
    { regex: /^df_ts/, company: "LinkedIN" },
    { regex: /^interstitial_page_reg_oauth_url/, company: "LinkedIN" },
    { regex: /^IRLD/, company: "LinkedIN" },
    { regex: /^l_page/, company: "LinkedIN" },
    { regex: /^lang/, company: "LinkedIN" },
    { regex: /^li_cc/, company: "LinkedIN" },
    { regex: /^li_feed_xray/, company: "LinkedIN" },
    { regex: /^li_oatml/, company: "LinkedIN" },
    { regex: /^li_sugr/, company: "LinkedIN" },
    { regex: /^liap/, company: "LinkedIN" },
    { regex: /^lidc/, company: "LinkedIN" },
    { regex: /^lissc/, company: "LinkedIN" },
    { regex: /^lms_ads/, company: "LinkedIN" },
    { regex: /^ln_or/, company: "LinkedIN" },
    { regex: /^lss_bundle_viewer/, company: "LinkedIN" },
    { regex: /^Performance CookiesSyncHistory/, company: "LinkedIN" },
    { regex: /^queryString/, company: "LinkedIN" },
    { regex: /^sharebox-suggestion/, company: "LinkedIN" },
    { regex: /^spectroscopyId/, company: "LinkedIN" },
    { regex: /^trkCode/, company: "LinkedIN" },
    { regex: /^trkInfo/, company: "LinkedIN" },
    { regex: /^UserMatchHistory/, company: "LinkedIN" },
    { regex: /^VID$/, company: "LinkedIN" },
    { regex: /^li_gc/, company: "LinkedIN" },
    { regex: /^bcookie/, company: "LinkedIN" },
    { regex: /^BizoUserMatchHistory/, company: "LinkedIN" },
    { regex: /^pxrc/, company: "Live Ramp Inc." },
    { regex: /^lidid/, company: "LiveIntent" },
    { regex: /^euconsent/, company: "LiveRamp" },
    { regex: /^panoramaId/, company: "Lotame" },
    { regex: /^panoramaId_expiry/, company: "Lotame" },
    { regex: /^panoramaId_expiry_exp/, company: "Lotame" },
    { regex: /^_cc_aud/, company: "Lotame" },
    { regex: /^_cc_id/, company: "Lotame" },
    { regex: /^_cc_dc/, company: "Lotatme" },
    { regex: /^audit/, company: "Magnite" },
    { regex: /^c$/, company: "Magnite" },
    { regex: /^khaos/, company: "Magnite" },
    { regex: /^put_/, company: "Magnite" },
    { regex: /^rpb$/, company: "Magnite" },
    { regex: /^rpx$/, company: "Magnite" },
    { regex: /^tv_U/, company: "Magnite" },
    { regex: /^tvid/, company: "Magnite" },
    { regex: /^mc_cid/, company: "Mailchimp" },
    { regex: /^mc_eid/, company: "Mailchimp" },
    { regex: /^mc_landing_site/, company: "Mailchimp" },
    { regex: /^mailmunch_second_pageview/, company: "MailMunch" },
    { regex: /^compass_sid/, company: "Marfeel" },
    { regex: /^compass_uid/, company: "Marfeel" },
    { regex: /^_mkto_trk/, company: "Marketo" },
    { regex: /^matomo_ignore/, company: "Matomo" },
    { regex: /^matomo_sessid/, company: "Matomo" },
    { regex: /^mtm_consent/, company: "Matomo" },
    { regex: /^mtm_consent_removed/, company: "Matomo" },
    { regex: /^mtm_cookie_consent/, company: "Matomo" },
    { regex: /^id$/, company: "Media Innovation Group" },
    { regex: /^ov$/, company: "Media Innovation Group" },
    { regex: /^mdata/, company: "Media Innovation Group" },
    { regex: /^data-$/, company: "Media.net" },
    { regex: /^gdpr_status/, company: "Media.net" },
    { regex: /^mnet_session_depth/, company: "Media.net" },
    { regex: /^visitor-id/, company: "Media.net" },
    { regex: /^mt_misc/, company: "MediaMath" },
    { regex: /^mt_mop/, company: "MediaMath" },
    { regex: /^uuid/, company: "MediaMath" },
    { regex: /^uuidc/, company: "MediaMath" },
    { regex: /^rts$/, company: "Mediaplex" },
    { regex: /^svid/, company: "Mediaplex" },
    { regex: /^mics_lts/, company: "Mediarithmics" },
    { regex: /^mics_uaid/, company: "Mediarithmics" },
    { regex: /^mics_vid/, company: "Mediarithmics" },
    { regex: /^am_tokens/, company: "MediaVine" },
    { regex: /^am_tokens_invalidate-verizon-pushes/, company: "MediaVine" },
    { regex: /^mv_tokens/, company: "MediaVine" },
    { regex: /^mv_tokens_invalidate-verizon-pushes/, company: "MediaVine" },
    { regex: /^edsid/, company: "MercadoLibre" },
    { regex: /^ftid/, company: "MercadoLibre" },
    { regex: /^stmat/, company: "Miaozhen Systems" },
    { regex: /^tsc$/, company: "Miaozhen Systems" },
    { regex: /^CLID/, company: "Microsoft Clarity" },
    { regex: /^MicrosoftApplicationsTelemetryDeviceId/, company: "Microsoft" },
    { regex: /^X-FD-FEATURES/, company: "Microsoft" },
    { regex: /^X-FD-Time/, company: "Microsoft" },
    { regex: /^MUID/, company: "Microsoft (Bing)" },
    { regex: /^SRM_B/, company: "Microsoft (Bing)" },
    { regex: /^_uetsid/, company: "Microsoft (Bing)" },
    { regex: /^_uetvid/, company: "Microsoft (Bing)" },
    { regex: /^SRCHHPGUSR/, company: "Microsoft (Bing)" },
    { regex: /^ANONCHK/, company: "Microsoft Clarity" },
    { regex: /^_clsk/, company: "Microsoft Clarity" },
    { regex: /^mp_$/, company: "Mixpanel" },
    { regex: /^Pastease.passive.activated/, company: "Mopinion.com" },
    { regex: /^Pastease.passive.chance/, company: "Mopinion.com" },
    { regex: /^mousestats_vi/, company: "MouseStats" },
    { regex: /^MR$/, company: "MSN" },
    { regex: /^SM$/, company: "MSN" },
    { regex: /^SRCHUSR/, company: "MSN" },
    { regex: /^SRCHUID/, company: "MSN" },
    { regex: /^SRCHD/, company: "MSN" },
    { regex: /^_EDGE_V/, company: "MSN" },
    { regex: /^MSPTC/, company: "MSPTC" },
    { regex: /^opt_out/, company: "Nativo" },
    { regex: /^visitor/, company: "Nativo" },
    { regex: /^uid_/, company: "NetworkAd.net" },
    { regex: /^n360_adform/, company: "Nexx360" },
    { regex: /^n360_adnuntius/, company: "Nexx360" },
    { regex: /^n360_adot/, company: "Nexx360" },
    { regex: /^n360_adyoulike/, company: "Nexx360" },
    { regex: /^n360_amx/, company: "Nexx360" },
    { regex: /^n360_appnexus/, company: "Nexx360" },
    { regex: /^n360_bliink/, company: "Nexx360" },
    { regex: /^n360_connectad/, company: "Nexx360" },
    { regex: /^n360_conversant/, company: "Nexx360" },
    { regex: /^n360_cwire/, company: "Nexx360" },
    { regex: /^n360_firstid/, company: "Nexx360" },
    { regex: /^n360_freewheel/, company: "Nexx360" },
    { regex: /^n360_fueldigital/, company: "Nexx360" },
    { regex: /^n360_fueldigitalix/, company: "Nexx360" },
    { regex: /^n360_fueldigitalmedia/, company: "Nexx360" },
    { regex: /^n360_gingerad/, company: "Nexx360" },
    { regex: /^n360_goodad/, company: "Nexx360" },
    { regex: /^n360_gravity/, company: "Nexx360" },
    { regex: /^n360_groupm/, company: "Nexx360" },
    { regex: /^n360_improve/, company: "Nexx360" },
    { regex: /^n360_ix/, company: "Nexx360" },
    { regex: /^n360_mediagrid/, company: "Nexx360" },
    { regex: /^n360_medianet/, company: "Nexx360" },
    { regex: /^n360_moneytag/, company: "Nexx360" },
    { regex: /^n360_nextmillennium/, company: "Nexx360" },
    { regex: /^n360_onetag/, company: "Nexx360" },
    { regex: /^n360_openx/, company: "Nexx360" },
    { regex: /^n360_outbrain/, company: "Nexx360" },
    { regex: /^n360_plista/, company: "Nexx360" },
    { regex: /^n360_pubmatic/, company: "Nexx360" },
    { regex: /^n360_pulsepoint/, company: "Nexx360" },
    { regex: /^n360_quantum/, company: "Nexx360" },
    { regex: /^n360_richaudience/, company: "Nexx360" },
    { regex: /^n360_rtbhouse/, company: "Nexx360" },
    { regex: /^n360_rubicon/, company: "Nexx360" },
    { regex: /^n360_sharethrough/, company: "Nexx360" },
    { regex: /^n360_smaato/, company: "Nexx360" },
    { regex: /^n360_smartadserver/, company: "Nexx360" },
    { regex: /^n360_smartyads/, company: "Nexx360" },
    { regex: /^n360_smilewanted/, company: "Nexx360" },
    { regex: /^n360_staila/, company: "Nexx360" },
    { regex: /^n360_tappx/, company: "Nexx360" },
    { regex: /^n360_thirtythreeacross/, company: "Nexx360" },
    { regex: /^n360_traffective/, company: "Nexx360" },
    { regex: /^n360_triplelift/, company: "Nexx360" },
    { regex: /^n360_ttd/, company: "Nexx360" },
    { regex: /^n360_vidoomy/, company: "Nexx360" },
    { regex: /^n360_yahoo/, company: "Nexx360" },
    { regex: /^n360_yieldlab/, company: "Nexx360" },
    { regex: /^n360-adform/, company: "Nexx360" },
    { regex: /^n360-adnuntius/, company: "Nexx360" },
    { regex: /^n360-adot/, company: "Nexx360" },
    { regex: /^n360-adyoulike/, company: "Nexx360" },
    { regex: /^n360-amx/, company: "Nexx360" },
    { regex: /^n360-appnexus/, company: "Nexx360" },
    { regex: /^n360-bliink/, company: "Nexx360" },
    { regex: /^n360-connectad/, company: "Nexx360" },
    { regex: /^n360-conversant/, company: "Nexx360" },
    { regex: /^n360-cwire/, company: "Nexx360" },
    { regex: /^n360-firstid/, company: "Nexx360" },
    { regex: /^n360-freewheel/, company: "Nexx360" },
    { regex: /^n360-fueldigital/, company: "Nexx360" },
    { regex: /^n360-fueldigitalix/, company: "Nexx360" },
    { regex: /^n360-fueldigitalmedia/, company: "Nexx360" },
    { regex: /^n360-gingerad/, company: "Nexx360" },
    { regex: /^n360-goodad/, company: "Nexx360" },
    { regex: /^n360-gravity/, company: "Nexx360" },
    { regex: /^n360-groupm/, company: "Nexx360" },
    { regex: /^n360-improve/, company: "Nexx360" },
    { regex: /^n360-ix/, company: "Nexx360" },
    { regex: /^n360-mediagrid/, company: "Nexx360" },
    { regex: /^n360-medianet/, company: "Nexx360" },
    { regex: /^n360-moneytag/, company: "Nexx360" },
    { regex: /^n360-nextmillennium/, company: "Nexx360" },
    { regex: /^n360-onetag/, company: "Nexx360" },
    { regex: /^n360-openx/, company: "Nexx360" },
    { regex: /^n360-outbrain/, company: "Nexx360" },
    { regex: /^n360-plista/, company: "Nexx360" },
    { regex: /^n360-pubmatic/, company: "Nexx360" },
    { regex: /^n360-pulsepoint/, company: "Nexx360" },
    { regex: /^n360-quantum/, company: "Nexx360" },
    { regex: /^n360-richaudience/, company: "Nexx360" },
    { regex: /^n360-rtbhouse/, company: "Nexx360" },
    { regex: /^n360-rubicon/, company: "Nexx360" },
    { regex: /^n360-sharethrough/, company: "Nexx360" },
    { regex: /^n360-smaato/, company: "Nexx360" },
    { regex: /^n360-smartadserver/, company: "Nexx360" },
    { regex: /^n360-smartyads/, company: "Nexx360" },
    { regex: /^n360-smilewanted/, company: "Nexx360" },
    { regex: /^n360-staila/, company: "Nexx360" },
    { regex: /^n360-tappx/, company: "Nexx360" },
    { regex: /^n360-thirtythreeacross/, company: "Nexx360" },
    { regex: /^n360-traffective/, company: "Nexx360" },
    { regex: /^n360-triplelift/, company: "Nexx360" },
    { regex: /^n360-ttd/, company: "Nexx360" },
    { regex: /^n360-vidoomy/, company: "Nexx360" },
    { regex: /^n360-yahoo/, company: "Nexx360" },
    { regex: /^n360-yieldlab/, company: "Nexx360" },
    { regex: /^EE$/, company: "Nielsen" },
    { regex: /^IMRID/, company: "Nielsen" },
    { regex: /^ud$/, company: "Nielsen" },
    { regex: /^udo$/, company: "Nielsen" },
    { regex: /^SSCVER/, company: "Nielsen" },
    { regex: /^ometria/, company: "Omertria" },
    { regex: /^done_redirects/, company: "OnAudience" },
    { regex: /^OAID/, company: "OpenX" },
    { regex: /^i$/, company: "openx.net" },
    { regex: /^OAGEO/, company: "openx.net" },
    { regex: /^pd$/, company: "openx.net" },
    { regex: /^univ_id/, company: "openx.net" },
    { regex: /^optimizelyDomainTestCookie/, company: "Optimizely" },
    { regex: /^optimizelyEndUserId/, company: "Optimizely" },
    { regex: /^optimizelyOptOut/, company: "Optimizely" },
    { regex: /^optimizelyRedirectData/, company: "Optimizely" },
    { regex: /^ELOQUA/, company: "Oracle" },
    { regex: /^ELQSTATUS/, company: "Oracle" },
    { regex: /^oribi_cookie_test/, company: "Oribi" },
    { regex: /^oribi_user_guid/, company: "Oribi" },
    { regex: /^adx_ts/, company: "Ortec" },
    { regex: /^app_ts/, company: "Ortec" },
    { regex: /^id_ts/, company: "Ortec" },
    { regex: /^spx_ts/, company: "Ortec" },
    { regex: /^viewer/, company: "Ortec" },
    { regex: /^adrl/, company: "Outbrain" },
    { regex: /^apnxs/, company: "Outbrain" },
    { regex: /^cookieJartestCookie/, company: "Outbrain" },
    { regex: /^criteo/, company: "Outbrain" },
    { regex: /^dicbo_id/, company: "Outbrain" },
    { regex: /^europe/, company: "Outbrain" },
    { regex: /^mdfrc/, company: "Outbrain" },
    { regex: /^obsessionid-/, company: "Outbrain" },
    { regex: /^obuid/, company: "Outbrain" },
    { regex: /^opout/, company: "Outbrain" },
    { regex: /^outbrain_dicbo_id/, company: "Outbrain" },
    { regex: /^recs/, company: "Outbrain" },
    { regex: /^recs-/, company: "Outbrain" },
    { regex: /^ref-/, company: "Outbrain" },
    { regex: /^ttd$/, company: "Outbrain" },
    { regex: /^unifiedPixel/, company: "Outbrain" },
    { regex: /^tPHG-PS/, company: "Partnerize" },
    { regex: /^pa_google_ts/, company: "Perfect Audience" },
    { regex: /^pa_openx_ts/, company: "Perfect Audience" },
    { regex: /^pa_rubicon_ts/, company: "Perfect Audience" },
    { regex: /^pa_twitter_ts/, company: "Perfect Audience" },
    { regex: /^pa_uid/, company: "Perfect Audience" },
    { regex: /^pa_yahoo_ts/, company: "Perfect Audience" },
    { regex: /^cX_G/, company: "Piano" },
    { regex: /^cX_P/, company: "Piano" },
    { regex: /^pa_user/, company: "Piano" },
    { regex: /^pnespsdk_pnespid/, company: "Piano" },
    { regex: /^pnespsdk_push_subscription_added/, company: "Piano" },
    { regex: /^pnespsdk_visitor/, company: "Piano" },
    { regex: /^picreel_new_price/, company: "Picreel" },
    { regex: /^picreel_tracker__first_visit/, company: "Picreel" },
    { regex: /^picreel_tracker__page_views/, company: "Picreel" },
    { regex: /^picreel_tracker__visited/, company: "Picreel" },
    { regex: /^sessionFunnelEventLogged/, company: "Pinterest" },
    { regex: /^_pinterest_ct_ua/, company: "Pinterest" },
    { regex: /^ppms_privacy_/, company: "Piwik" },
    { regex: /^ppms_privacy_bar_/, company: "Piwik" },
    { regex: /^stg_externalReferrer/, company: "Piwik" },
    { regex: /^stg_fired__/, company: "Piwik" },
    { regex: /^stg_global_opt_out/, company: "Piwik" },
    { regex: /^stg_last_interaction/, company: "Piwik" },
    { regex: /^stg_pk_campaign/, company: "Piwik" },
    { regex: /^stg_returning_visitor/, company: "Piwik" },
    { regex: /^stg_traffic_source_priority/, company: "Piwik" },
    { regex: /^stg_utm_campaign/, company: "Piwik" },
    { regex: /^pys_utm_campaign/, company: "PixelYourSite" },
    { regex: /^pys_utm_term/, company: "PixelYourSite" },
    { regex: /^pysTrafficSource/, company: "PixelYourSite" },
    { regex: /^last_pysTrafficSource/, company: "PixelYourSite" },
    { regex: /^last_pys_landing_page/, company: "PixelYourSite" },
    { regex: /^pys_utm_medium/, company: "PixelYourSite" },
    { regex: /^last_pys_utm_campaign/, company: "PixelYourSite" },
    { regex: /^pys_padid/, company: "PixelYourSite" },
    { regex: /^last_pys_utm_content/, company: "PixelYourSite" },
    { regex: /^last_pys_utm_medium/, company: "PixelYourSite" },
    { regex: /^last_pys_padid/, company: "PixelYourSite" },
    { regex: /^last_pys_utm_source/, company: "PixelYourSite" },
    { regex: /^pys_landing_page/, company: "PixelYourSite" },
    { regex: /^pys_first_visit/, company: "PixelYourSite" },
    { regex: /^last_pys_bingid/, company: "PixelYourSite" },
    { regex: /^ad2$/, company: "Platform161" },
    { regex: /^fl_inst/, company: "Platform161" },
    { regex: /^pcc2/, company: "Platform161" },
    { regex: /^pvc2/, company: "Platform161" },
    { regex: /^trc$/, company: "Platform161" },
    { regex: /^pvc_visits[0]/, company: "Postviewscounter" },
    { regex: /^pl_user_id/, company: "PowerLinks" },
    { regex: /^dsps:/, company: "PowerLinks Media Limited" },
    { regex: /^ADUSERCOOKIE/, company: "PubMatic" },
    { regex: /^camfreq_/, company: "PubMatic" },
    { regex: /^DPFQ/, company: "PubMatic" },
    { regex: /^DPPIX_ON/, company: "PubMatic" },
    { regex: /^DPSync/, company: "PubMatic" },
    { regex: /^f5_cspm/, company: "PubMatic" },
    { regex: /^KADUSERCOOKIE/, company: "Pubmatic" },
    { regex: /^KCCH/, company: "PubMatic" },
    { regex: /^KRTBCOOKIE_/, company: "Pubmatic" },
    { regex: /^pi$/, company: "PubMatic" },
    { regex: /^pp$/, company: "PubMatic" },
    { regex: /^pubfreq_/, company: "PubMatic" },
    { regex: /^PUBMDCID/, company: "PubMatic" },
    { regex: /^PUBRETARGET/, company: "PubMatic" },
    { regex: /^PugT/, company: "Pubmatic" },
    { regex: /^SPugT/, company: "PubMatic" },
    { regex: /^SyncRTB/, company: "PubMatic" },
    { regex: /^SYNCUPPIX_ON/, company: "PubMatic" },
    { regex: /^USCC/, company: "PubMatic" },
    { regex: /^KTPCACOOKIE/, company: "Pubmatic" },
    { regex: /^ki_s/, company: "Qualaroo" },
    { regex: /^ki_t/, company: "Qualaroo" },
    { regex: /^ki_u/, company: "Qualaroo" },
    { regex: /^ActionSetHistory/, company: "Qualtrics" },
    { regex: /^BlurTime/, company: "Qualtrics" },
    { regex: /^CPSessID/, company: "Qualtrics" },
    { regex: /^FocusTime/, company: "Qualtrics" },
    { regex: /^PageReferrer/, company: "Qualtrics" },
    { regex: /^QSI_HistorySession/, company: "Qualtrics" },
    { regex: /^QSI_OptInIDsAndTargetOrigins/, company: "Qualtrics" },
    { regex: /^QSI_OptInIDsAndWindowNames/, company: "Qualtrics" },
    { regex: /^QSI_ReplaySession_Info_/, company: "Qualtrics" },
    { regex: /^QSI_SI_/, company: "Qualtrics" },
    { regex: /^QSI_TestSessions_/, company: "Qualtrics" },
    { regex: /^SearchTerm/, company: "Qualtrics" },
    { regex: /^SISessID/, company: "Qualtrics" },
    { regex: /^SiteReferrer/, company: "Qualtrics" },
    { regex: /^cref/, company: "Quantcast" },
    { regex: /^d$/, company: "Quantcast" },
    { regex: /^mc$/, company: "Quantcast" },
    { regex: /^_qubitTracker_s/, company: "Qubit" },
    { regex: /^_qsst/, company: "Qubit" },
    { regex: /^_qsst_s/, company: "Qubit" },
    { regex: /^qb_permanent/, company: "Qubit" },
    { regex: /^edgebucket/, company: "Reddit" },
    { regex: /^initref/, company: "Reddit" },
    { regex: /^rek_content/, company: "rekmob.com" },
    { regex: /^act$/, company: "Rely42" },
    { regex: /^pdid/, company: "richAudience" },
    { regex: /^rai-pltn-pl-/, company: "richAudience" },
    { regex: /^rlas3/, company: "rlcdn.com" },
    { regex: /^rud$/, company: "Rocketfuel" },
    { regex: /^eud$/, company: "Rocketfuel" },
    { regex: /^ruds/, company: "Rocketfuel" },
    { regex: /^euds/, company: "Rocketfuel" },
    { regex: /^matchadform/, company: "Roku" },
    { regex: /^rl_anonymous_id/, company: "Rudderstack" },
    { regex: /^rl_auth_token/, company: "Rudderstack" },
    { regex: /^rl_group_id/, company: "Rudderstack" },
    { regex: /^rl_group_trait/, company: "Rudderstack" },
    { regex: /^rl_page_init_referrer/, company: "Rudderstack" },
    { regex: /^rl_page_init_referring_domain/, company: "Rudderstack" },
    { regex: /^rl_session/, company: "Rudderstack" },
    { regex: /^rl_trait/, company: "Rudderstack" },
    { regex: /^rl_user_id/, company: "Rudderstack" },
    { regex: /^test_rudder_cookie/, company: "Rudderstack" },
    { regex: /^sailthru_content/, company: "Sailthru" },
    { regex: /^sailthru_pageviews/, company: "Sailthru" },
    { regex: /^sailthru_visitor/, company: "Sailthru" },
    { regex: /^apex__EmailAddress/, company: "Salesforce" },
    { regex: /^auraBrokenDefGraph/, company: "Salesforce" },
    { regex: /^calViewState/, company: "Salesforce" },
    { regex: /^expid_/, company: "Salesforce" },
    { regex: /^oinfo/, company: "Salesforce" },
    { regex: /^pctrk/, company: "Salesforce" },
    { regex: /^visitor_id/, company: "Salesforce" },
    { regex: /^awx$/, company: "Salesforce" },
    { regex: /^apiDomain_/, company: "SAP" },
    { regex: /^gig_bootstrap_/, company: "SAP" },
    { regex: /^gig_hasGmid/, company: "SAP" },
    { regex: /^gmid/, company: "SAP" },
    { regex: /^st_chc/, company: "Seedtag" },
    { regex: /^st_cnt/, company: "Seedtag" },
    { regex: /^st_ssp/, company: "Seedtag" },
    { regex: /^st_uid/, company: "Seedtag" },
    { regex: /^st_cs/, company: "Seedtag" },
    { regex: /^st_csd/, company: "Seedtag" },
    { regex: /^SEUNCY/, company: "semasio.net" },
    { regex: /^pxcelBcnLcy/, company: "ShareThis" },
    { regex: /^pxcelPage/, company: "ShareThis" },
    { regex: /^stx_user_id/, company: "Sharethrough" },
    { regex: /^koitk/, company: "Sharpspring" },
    { regex: /^ki_r/, company: "Shopify" },
    { regex: /^nmstat/, company: "Siteimprove" },
    { regex: /^ssi$/, company: "SiteScout" },
    { regex: /^_ssuma/, company: "SiteScout" },
    { regex: /^SCM$/, company: "Smaato" },
    { regex: /^SCM*/, company: "Smaato" },
    { regex: /^SCMaps/, company: "Smaato" },
    { regex: /^SCMg/, company: "Smaato" },
    { regex: /^SCMinf/, company: "Smaato" },
    { regex: /^SCMo/, company: "Smaato" },
    { regex: /^SCMsovrn/, company: "Smaato" },
    { regex: /^cnfq/, company: "Smartadserver" },
    { regex: /^Comp/, company: "Smartadserver" },
    { regex: /^csfq/, company: "Smartadserver" },
    { regex: /^csync/, company: "Smartadserver" },
    { regex: /^gid$/, company: "Smartadserver" },
    { regex: /^lcsrc/, company: "Smartadserver" },
    { regex: /^lcsrd/, company: "Smartadserver" },
    { regex: /^partner-/, company: "Smartadserver" },
    { regex: /^pbw$/, company: "Smartadserver" },
    { regex: /^Pwb$/, company: "Smartadserver" },
    { regex: /^sasd/, company: "Smartadserver" },
    { regex: /^sasd2/, company: "Smartadserver" },
    { regex: /^TestIfCookie/, company: "Smartadserver" },
    { regex: /^TestIfCookieP/, company: "Smartadserver" },
    { regex: /^vs$/, company: "Smartadserver" },
    { regex: /^psyn/, company: "SmartClip" },
    { regex: /^sc_at/, company: "Snapchat" },
    { regex: /^sc-a-nonce/, company: "Snapchat" },
    { regex: /^SnapABugHistory/, company: "SnapEngage" },
    { regex: /^SnapABugRef/, company: "SnapEngage" },
    { regex: /^sp$/, company: "Snowplow" },
    { regex: /^HAPLB3A/, company: "Sonobi" },
    { regex: /^HAPLB5S/, company: "Sonobi" },
    { regex: /^HAPLB8/, company: "Sonobi" },
    { regex: /^sc_anonymous_id/, company: "Soundcloud" },
    { regex: /^ljtrtb/, company: "SOVRN" },
    { regex: /^audience/, company: "Spotxchange" },
    { regex: /^sst$/, company: "Springserve" },
    { regex: /^sqzl_abs/, company: "Squeezely" },
    { regex: /^sqzl_session_id/, company: "Squeezely" },
    { regex: /^sqzl_vw/, company: "Squeezely" },
    { regex: /^sqzllocal/, company: "Squeezely" },
    { regex: /^MRM_UID/, company: "StickyAdsTV" },
    { regex: /^uid-bp-/, company: "StickyAdsTV" },
    { regex: /^idsync-bsw-uid-s/, company: "StreamTheWorld" },
    { regex: /^sskyCreationTime/, company: "SundaySky" },
    { regex: /^sskya/, company: "SundaySky" },
    { regex: /^sm_user_id/, company: "SuveyMonkey" },
    { regex: /^abLdr/, company: "Taboola" },
    { regex: /^abMbl/, company: "Taboola" },
    { regex: /^t_gid/, company: "Taboola" },
    { regex: /^taboola_session_id/, company: "Taboola" },
    { regex: /^tb_click_param/, company: "Taboola" },
    { regex: /^n$/, company: "Tailtarget" },
    { regex: /^trk$/, company: "Tailtarget" },
    { regex: /^ttbprf/, company: "Tailtarget" },
    { regex: /^ttc$/, company: "Tailtarget" },
    { regex: /^ttca/, company: "Tailtarget" },
    { regex: /^ttgcm/, company: "Tailtarget" },
    { regex: /^ttnprf/, company: "Tailtarget" },
    { regex: /^TapAd_3WAY_SYNCS/, company: "TapAd" },
    { regex: /^TapAd_DID/, company: "TapAd" },
    { regex: /^TapAd_TS/, company: "TapAd" },
    { regex: /^TXCD/, company: "Tappx" },
    { regex: /^TXCSDMN_/, company: "Tappx" },
    { regex: /^tawkUUID/, company: "Tawk.to Chat" },
    { regex: /^tt_bluekai/, company: "Teads" },
    { regex: /^tt_exelate/, company: "Teads" },
    { regex: /^tt_liveramp/, company: "Teads" },
    { regex: /^tt_neustar/, company: "Teads" },
    { regex: /^tt_salesforce/, company: "Teads" },
    { regex: /^tt_viewer/, company: "Teads" },
    { regex: /^ozone_uid/, company: "The Ozone Project" },
    { regex: /^TDCPM/, company: "The Tradedesk" },
    { regex: /^TDID/, company: "The Tradedesk" },
    { regex: /^MONITOR_WEB_ID/, company: "TikTok" },
    { regex: /^msToken/, company: "TikTok" },
    { regex: /^ttwid/, company: "TikTok" },
    { regex: /^ServerPool/, company: "Tripadvisor" },
    { regex: /^TADCID/, company: "Tripadvisor" },
    { regex: /^TAReturnTo/, company: "Tripadvisor" },
    { regex: /^TATravelInfo/, company: "Tripadvisor" },
    { regex: /^TAUnique/, company: "Tripadvisor" },
    { regex: /^optout/, company: "TripleLift" },
    { regex: /^sync/, company: "TripleLift" },
    { regex: /^tluid/, company: "TripleLift" },
    { regex: /^tluidp/, company: "TripleLift" },
    { regex: /^ajs_anonymous_id/, company: "Trustpilot" },
    { regex: /^ajs_group_id/, company: "Trustpilot" },
    { regex: /^ajs_user_id/, company: "Trustpilot" },
    { regex: /^amplitude_id/, company: "Trustpilot" },
    { regex: /^deuxesse_uxid/, company: "Twiago" },
    { regex: /^muc_ads/, company: "Twitter" },
    { regex: /^personalization_id/, company: "Twitter" },
    { regex: /^pid$/, company: "Twitter" },
    { regex: /^dt$/, company: "Underdog Media" },
    { regex: /^rtbh/, company: "Underdog Media" },
    { regex: /^udmts/, company: "Underdog Media" },
    { regex: /^UID_EXT_*/, company: "Undertone" },
    { regex: /^UTID/, company: "Undertone" },
    { regex: /^UTID_ENC/, company: "Undertone" },
    { regex: /^unruly_m/, company: "Unrulymedia.com" },
    { regex: /^usbls/, company: "Usabilla" },
    { regex: /^lkqdid/, company: "Verve" },
    { regex: /^lkqdidts/, company: "Verve" },
    { regex: /^UIXX_UPDT/, company: "VideoHub.tv" },
    { regex: /^Vo$/, company: "Videology" },
    { regex: /^vidoomy-uids/, company: "Vidoomy" },
    { regex: /^sd_client_id/, company: "Vimeo" },
    { regex: /^sd_identity/, company: "Vimeo" },
    { regex: /^vuid/, company: "Vimeo" },
    { regex: /^um2$/, company: "Visx.net" },
    { regex: /^BSWtracker/, company: "vmg.host" },
    { regex: /^_vwo_uuid_v2/, company: "VWO" },
    { regex: /^_vis_opt_s/, company: "VWO" },
    { regex: /^_vwo_referrer/, company: "VWO" },
    { regex: /^_vwo_uuid/, company: "VWO" },
    { regex: /^^_vis_opt_exp_n_goal_n/, company: "VWO" },
    { regex: /^_vwo_sn/, company: "VWO" },
    { regex: /^_vwo_ds/, company: "VWO" },
    { regex: /^_vis_opt_exp_n_combi/, company: "VWO" },
    { regex: /^_vis_opt_test_cookie/, company: "VWO" },
    { regex: /^wfivefivec/, company: "W55c.net" },
    { regex: /^s_vi/, company: "Adobe Marketing Cloud" },
    { regex: /^AFFICHE_W/, company: "Weborama" },
    { regex: /^centralnotice_bucket/, company: "Wikimedia" },
    { regex: /^GeoIP/, company: "Wikimedia" },
    { regex: /^NetWorkProbeLimit/, company: "Wikimedia" },
    { regex: /^WMF-Last-Access/, company: "Wikimedia" },
    { regex: /^icu$/, company: "Xandr" },
    { regex: /^pses/, company: "Xandr" },
    { regex: /^uids/, company: "Xandr" },
    { regex: /^usersync/, company: "Xandr" },
    { regex: /^XANDR_PANID/, company: "Xandr" },
    { regex: /^adaptv_unique_user_cookie/, company: "Yahoo" },
    { regex: /^adsrcvw1/, company: "Yahoo" },
    { regex: /^APID/, company: "Yahoo" },
    { regex: /^APIDTS/, company: "Yahoo" },
    { regex: /^cmp$/, company: "Yahoo" },
    { regex: /^GUC$/, company: "Yahoo" },
    { regex: /^IDSYNC/, company: "Yahoo" },
    { regex: /^migrated2y/, company: "Yahoo" },
    { regex: /^OTH$/, company: "Yahoo" },
    { regex: /^rtbData0/, company: "Yahoo" },
    { regex: /^rxx$/, company: "Yahoo" },
    { regex: /^tbla_id/, company: "Yahoo" },
    { regex: /^tearsheet/, company: "Yahoo" },
    { regex: /^trc_cookie_storage/, company: "Yahoo" },
    { regex: /^unique_ad_source_impression/, company: "Yahoo" },
    { regex: /^A1S$/, company: "Yahoo" },
    { regex: /^A3$/, company: "Yahoo" },
    { regex: /^A1$/, company: "Yahoo" },
    { regex: /^B$/, company: "Yahoo" },
    { regex: /^yandexuid/, company: "Yandex" },
    { regex: /^yashr/, company: "Yandex" },
    { regex: /^metrika_enabled/, company: "Yandex" },
    { regex: /^_ym_d/, company: "Yandex" },
    { regex: /^_ym_isad/, company: "Yandex" },
    { regex: /^bh$/, company: "Yandex" },
    { regex: /^is_gdpr/, company: "Yandex" },
    { regex: /^is_gdpr_b/, company: "Yandex" },
    { regex: /^usst/, company: "Yandex" },
    { regex: /^yabs-sid/, company: "Yandex" },
    { regex: /^yabs-vdrf/, company: "Yandex" },
    { regex: /^ymex/, company: "Yandex" },
    { regex: /^yuidss/, company: "Yandex" },
    { regex: /^ptradtrt/, company: "Yieldmo" },
    { regex: /^ptran/, company: "Yieldmo" },
    { regex: /^ptrb/, company: "Yieldmo" },
    { regex: /^ptrbsw/, company: "Yieldmo" },
    { regex: /^ptrc/, company: "Yieldmo" },
    { regex: /^ptrcriteo/, company: "Yieldmo" },
    { regex: /^ptreps/, company: "Yieldmo" },
    { regex: /^ptropenx/, company: "Yieldmo" },
    { regex: /^ptrpp/, company: "Yieldmo" },
    { regex: /^ptrpub/, company: "Yieldmo" },
    { regex: /^ptrrc/, company: "Yieldmo" },
    { regex: /^ptrrhs/, company: "Yieldmo" },
    { regex: /^ptrt/, company: "Yieldmo" },
    { regex: /^yieldmo_id/, company: "Yieldmo" },
    { regex: /^GPS$/, company: "YouTube" },
    { regex: /^VISITOR_INFO1_LIVE/, company: "Youtube" },
    { regex: /^VISITOR_PRIVACY_METADATA/, company: "Youtube" },
    { regex: /^__Secure-YEC/, company: "YouTube" },
    { regex: /^ZD-buid/, company: "Zendesk" },
    { regex: /^ZD-suid/, company: "Zendesk" },
    { regex: /^idp$/, company: "Zeotap" },
    { regex: /^zc$/, company: "Zeotap" },
    { regex: /^zi$/, company: "Zeotap" },
    { regex: /^zsc$/, company: "Zeotap" },
    { regex: /^zuc$/, company: "Zeotap" },
    { regex: /^zc_loc/, company: "ZOHO" },
    { regex: /^zc_show/, company: "ZOHO" },
    { regex: /^s_vnc365/, company: "Adobe Experience Cloud" },

];